import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── colour palette ────────────────────────────────────────────────────────────
const C = {
  brand:    [16,  185, 129] as [number,number,number],   // emerald-500
  dark:     [17,  24,  39]  as [number,number,number],   // gray-900
  mid:      [55,  65,  81]  as [number,number,number],   // gray-700
  light:    [156, 163, 175] as [number,number,number],   // gray-400
  xlight:   [229, 231, 235] as [number,number,number],   // gray-200
  white:    [255, 255, 255] as [number,number,number],
  success:  [5,   150, 105] as [number,number,number],   // emerald-600
  warn:     [217, 119, 6]   as [number,number,number],   // amber-600
  danger:   [220, 38,  38]  as [number,number,number],   // red-600
  info:     [37,  99,  235] as [number,number,number],   // blue-600
  row_alt:  [249, 250, 251] as [number,number,number],   // gray-50
}

function severityColor(s: string): [number,number,number] {
  const sev = (s || '').toUpperCase()
  if (sev === 'CRITICAL') return C.danger
  if (sev === 'HIGH')     return [234, 88, 12]  // orange-600
  if (sev === 'MEDIUM')   return C.warn
  if (sev === 'LOW')      return C.info
  return C.light
}

// ── layout constants ──────────────────────────────────────────────────────────
const PW = 210   // A4 width mm
const PH = 297   // A4 height mm
const ML = 15    // left margin
const MR = 15    // right margin
const CW = PW - ML - MR  // content width

// ── helpers ───────────────────────────────────────────────────────────────────
function setFont(doc: jsPDF, size: number, style: 'normal'|'bold' = 'normal', color = C.dark) {
  doc.setFont('helvetica', style)
  doc.setFontSize(size)
  doc.setTextColor(...color)
}

function filledRect(doc: jsPDF, x: number, y: number, w: number, h: number, color: [number,number,number]) {
  doc.setFillColor(...color)
  doc.rect(x, y, w, h, 'F')
}

function addPageHeader(doc: jsPDF, pageNum: number, firmware: string) {
  filledRect(doc, 0, 0, PW, 10, C.dark)
  setFont(doc, 7, 'bold', C.brand)
  doc.text('FirmScan', ML, 6.5)
  setFont(doc, 7, 'normal', C.light)
  const trimmed = firmware.length > 60 ? firmware.slice(0, 57) + '…' : firmware
  doc.text(trimmed, ML + 20, 6.5)
  doc.text(`Page ${pageNum}`, PW - MR, 6.5, { align: 'right' })
}

function addPageFooter(doc: jsPDF, ts: string) {
  const y = PH - 7
  doc.setDrawColor(...C.xlight)
  doc.setLineWidth(0.3)
  doc.line(ML, y - 2, PW - MR, y - 2)
  setFont(doc, 6.5, 'normal', C.light)
  doc.text('Generated by FirmScan Security Framework', ML, y)
  doc.text(ts, PW - MR, y, { align: 'right' })
}

function ensureSpace(doc: jsPDF, cursor: number, need: number, firmware: string, ts: string, pages: { n: number }): number {
  if (cursor + need > PH - 15) {
    addPageFooter(doc, ts)
    doc.addPage()
    pages.n += 1
    addPageHeader(doc, pages.n, firmware)
    return 18
  }
  return cursor
}

function sectionHeading(doc: jsPDF, text: string, y: number): number {
  doc.setDrawColor(...C.brand)
  doc.setLineWidth(0.5)
  doc.line(ML, y, ML + CW, y)
  setFont(doc, 9, 'bold', C.dark)
  doc.text(text.toUpperCase(), ML, y + 5)
  return y + 10
}

// ── metric box ────────────────────────────────────────────────────────────────
function metricBox(
  doc: jsPDF,
  x: number, y: number, w: number, h: number,
  label: string, value: string,
  valueColor: [number,number,number] = C.dark
) {
  filledRect(doc, x, y, w, h, C.xlight)
  doc.setDrawColor(...C.xlight)
  doc.setLineWidth(0.3)
  doc.rect(x, y, w, h)
  setFont(doc, 14, 'bold', valueColor)
  doc.text(value, x + w / 2, y + h / 2 - 1, { align: 'center' })
  setFont(doc, 7, 'normal', C.light)
  doc.text(label, x + w / 2, y + h / 2 + 5, { align: 'center' })
}

// ── status pill ───────────────────────────────────────────────────────────────
function statusPill(doc: jsPDF, x: number, y: number, status: string) {
  const label = (status || 'unknown').replace(/_/g, ' ').toUpperCase()
  const color: [number,number,number] = status === 'success' ? C.success
    : status === 'emulation_failed' ? C.warn
    : C.danger
  const tw = doc.getTextWidth(label)
  const pw = tw + 8
  filledRect(doc, x, y - 4, pw, 6, color)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(...C.white)
  doc.text(label, x + 4, y)
  return pw
}

// ── main export function ──────────────────────────────────────────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function exportReportPdf(report: Record<string, any>) {
  const doc    = new jsPDF({ unit: 'mm', format: 'a4' })
  const pages  = { n: 1 }
  const ts     = new Date().toLocaleString()
  const fw     = (report.firmware  || {}) as Record<string, unknown>
  const em     = (report.emulation || {}) as Record<string, unknown>
  const pr     = (report.probe     || {}) as Record<string, unknown>
  const cves   = (report.cve_matches  as Record<string,unknown>[]) ?? []
  const creds  = (report.credentials  as Record<string,unknown>[]) ?? []
  const webs   = (report.web_findings as Record<string,unknown>[]) ?? []
  const svcs   = ((pr.services as Record<string,unknown>[]) ?? [])
  const fwName = String(fw.name ?? report.filename ?? 'Unknown')
  const status = String(
    report.status
    ?? (em.success ? 'success' : em.image_id != null ? 'emulation_failed' : 'unknown')
  )
  const validCreds = creds.filter(c => c.success)

  // ── cover / header band ───────────────────────────────────────────────────
  filledRect(doc, 0, 0, PW, 48, C.dark)

  // brand mark
  setFont(doc, 22, 'bold', C.brand)
  doc.text('FirmScan', ML, 18)
  setFont(doc, 9, 'normal', C.light)
  doc.text('Firmware Security Analysis Report', ML, 25)

  // firmware name
  setFont(doc, 11, 'bold', C.white)
  const nameLines = doc.splitTextToSize(fwName, CW - 10) as string[]
  doc.text(nameLines.slice(0, 2), ML, 34)

  // status pill
  setFont(doc, 7, 'bold', C.white)
  statusPill(doc, ML, 44, status)

  // thin green accent line
  filledRect(doc, 0, 48, PW, 1.5, C.brand)

  let y = 58

  // ── key metrics row ───────────────────────────────────────────────────────
  const bw = (CW - 9) / 4
  const bx = [ML, ML + bw + 3, ML + (bw + 3) * 2, ML + (bw + 3) * 3]

  metricBox(doc, bx[0], y, bw, 20, 'Services', String(svcs.length || 0), C.dark)
  metricBox(doc, bx[1], y, bw, 20, 'CVE Matches', String(cves.length || 0),
    cves.length > 0 ? C.danger : C.dark)
  metricBox(doc, bx[2], y, bw, 20, 'Web Findings', String(webs.length || 0),
    webs.length > 0 ? C.warn : C.dark)
  metricBox(doc, bx[3], y, bw, 20, 'Credentials', String(validCreds.length || 0),
    validCreds.length > 0 ? C.danger : C.dark)

  y += 26

  // ── meta table (2-column key/value grid) ──────────────────────────────────
  const meta: [string, string][] = [
    ['Run ID',        String(report.run_id ?? '—')],
    ['Timestamp',     report.timestamp ? new Date(String(report.timestamp)).toLocaleString() : '—'],
    ['Architecture',  String(em.architecture ?? '—')],
    ['IP Address',    String(em.ip ?? '—')],
    ['SHA-256',       String(fw.sha256 ?? '—').slice(0, 32) + (String(fw.sha256 ?? '').length > 32 ? '…' : '')],
    ['File Size',     fw.size_bytes ? `${(Number(fw.size_bytes) / 1e6).toFixed(2)} MB` : '—'],
    ['Profile',       String(pr.scan_profile ?? '—')],
    ['Scan Duration', pr.scan_duration_seconds ? `${pr.scan_duration_seconds}s` : '—'],
  ]

  const halfCW = (CW - 6) / 2
  meta.forEach(([k, v], i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const rx  = ML + col * (halfCW + 6)
    const ry  = y + row * 7
    if (col === 0 && i > 0 && i % 2 === 0) {
      // alternate row tint
      filledRect(doc, ML, ry - 1, CW, 7, row % 2 === 0 ? C.row_alt : C.white)
    }
    setFont(doc, 7.5, 'normal', C.light)
    doc.text(k, rx, ry + 4)
    setFont(doc, 7.5, 'bold', C.dark)
    doc.text(v, rx + halfCW / 2, ry + 4)
  })

  y += Math.ceil(meta.length / 2) * 7 + 8

  // ── page footer for page 1 ────────────────────────────────────────────────
  addPageHeader(doc, 1, fwName)
  addPageFooter(doc, ts)

  // ── services ──────────────────────────────────────────────────────────────
  if (svcs.length > 0) {
    doc.addPage(); pages.n++
    addPageHeader(doc, pages.n, fwName)
    y = 18
    y = sectionHeading(doc, `Services  (${svcs.length})`, y)

    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [['Port', 'Protocol', 'Service', 'Version']],
      body: svcs.map(s => [
        String(s.port ?? ''),
        String(s.protocol ?? ''),
        String(s.service ?? ''),
        String(s.version ?? ''),
      ]),
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: C.dark, textColor: C.white, fontStyle: 'bold', fontSize: 8 },
      columnStyles: {
        0: { cellWidth: 20, halign: 'right' },
        1: { cellWidth: 22 },
        2: { cellWidth: 40 },
        3: { cellWidth: 'auto' },
      },
      alternateRowStyles: { fillColor: C.row_alt },
      didDrawPage: () => {
        pages.n = (doc as jsPDF & { internal: { getCurrentPageInfo(): { pageNumber: number } } })
          .internal.getCurrentPageInfo().pageNumber
        addPageHeader(doc, pages.n, fwName)
        addPageFooter(doc, ts)
      },
    })
    y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10
    addPageFooter(doc, ts)
  }

  // ── CVE matches ───────────────────────────────────────────────────────────
  if (cves.length > 0) {
    doc.addPage(); pages.n++
    addPageHeader(doc, pages.n, fwName)
    y = 18
    y = sectionHeading(doc, `CVE Matches  (${cves.length})`, y)

    // severity summary bar
    const byCrit  = cves.filter(c => String(c.severity).toUpperCase() === 'CRITICAL').length
    const byHigh  = cves.filter(c => String(c.severity).toUpperCase() === 'HIGH').length
    const byMed   = cves.filter(c => String(c.severity).toUpperCase() === 'MEDIUM').length
    const byLow   = cves.filter(c => String(c.severity).toUpperCase() === 'LOW').length

    const pills: [string, number, [number,number,number]][] = [
      ['CRITICAL', byCrit, C.danger],
      ['HIGH',     byHigh, [234, 88, 12]],
      ['MEDIUM',   byMed,  C.warn],
      ['LOW',      byLow,  C.info],
    ]
    let px = ML
    pills.forEach(([label, count, color]) => {
      if (count === 0) return
      const txt = `${label}: ${count}`
      const tw  = doc.getTextWidth(txt) + 8
      filledRect(doc, px, y, tw, 6, color)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7)
      doc.setTextColor(...C.white)
      doc.text(txt, px + 4, y + 4)
      px += tw + 3
    })
    y += 10

    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [['CVE ID', 'Severity', 'CVSS', 'Port / Service', 'Description']],
      body: cves.map(c => [
        String(c.cve_id ?? ''),
        String(c.severity ?? ''),
        c.cvss_score != null ? String(c.cvss_score) : '—',
        `${c.port ?? ''}  ${c.service ?? ''} ${c.version ?? ''}`.trim(),
        String(c.description ?? '').slice(0, 120) + (String(c.description ?? '').length > 120 ? '…' : ''),
      ]),
      styles: { fontSize: 7.5, cellPadding: 2.5, overflow: 'linebreak' },
      headStyles: { fillColor: C.dark, textColor: C.white, fontStyle: 'bold', fontSize: 7.5 },
      columnStyles: {
        0: { cellWidth: 30, fontStyle: 'bold' },
        1: { cellWidth: 20, halign: 'center' },
        2: { cellWidth: 14, halign: 'center' },
        3: { cellWidth: 38 },
        4: { cellWidth: 'auto' },
      },
      alternateRowStyles: { fillColor: C.row_alt },
      didParseCell: (data) => {
        if (data.column.index === 1 && data.section === 'body') {
          const sev = String(data.cell.raw ?? '')
          data.cell.styles.textColor = severityColor(sev)
          data.cell.styles.fontStyle = 'bold'
        }
      },
      didDrawPage: () => {
        pages.n = (doc as jsPDF & { internal: { getCurrentPageInfo(): { pageNumber: number } } })
          .internal.getCurrentPageInfo().pageNumber
        addPageHeader(doc, pages.n, fwName)
        addPageFooter(doc, ts)
      },
    })
    addPageFooter(doc, ts)
  }

  // ── web findings ──────────────────────────────────────────────────────────
  if (webs.length > 0) {
    doc.addPage(); pages.n++
    addPageHeader(doc, pages.n, fwName)
    y = 18
    y = sectionHeading(doc, `Web Findings  (${webs.length})`, y)

    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [['Severity', 'Type', 'Port', 'Path', 'Detail']],
      body: webs.map(w => [
        String(w.severity ?? ''),
        String(w.finding_type ?? ''),
        String(w.port ?? ''),
        String(w.path ?? ''),
        String(w.detail ?? ''),
      ]),
      styles: { fontSize: 7.5, cellPadding: 2.5, overflow: 'linebreak' },
      headStyles: { fillColor: C.dark, textColor: C.white, fontStyle: 'bold', fontSize: 7.5 },
      columnStyles: {
        0: { cellWidth: 20, halign: 'center' },
        1: { cellWidth: 35 },
        2: { cellWidth: 14, halign: 'center' },
        3: { cellWidth: 35 },
        4: { cellWidth: 'auto' },
      },
      alternateRowStyles: { fillColor: C.row_alt },
      didParseCell: (data) => {
        if (data.column.index === 0 && data.section === 'body') {
          data.cell.styles.textColor = severityColor(String(data.cell.raw ?? ''))
          data.cell.styles.fontStyle = 'bold'
        }
      },
      didDrawPage: () => {
        pages.n = (doc as jsPDF & { internal: { getCurrentPageInfo(): { pageNumber: number } } })
          .internal.getCurrentPageInfo().pageNumber
        addPageHeader(doc, pages.n, fwName)
        addPageFooter(doc, ts)
      },
    })
    addPageFooter(doc, ts)
  }

  // ── credentials ───────────────────────────────────────────────────────────
  if (validCreds.length > 0) {
    doc.addPage(); pages.n++
    addPageHeader(doc, pages.n, fwName)
    y = 18

    // red warning banner
    filledRect(doc, ML, y, CW, 10, C.danger)
    setFont(doc, 9, 'bold', C.white)
    doc.text(`VALID CREDENTIALS FOUND  (${validCreds.length})`, ML + 4, y + 6.5)
    y += 14

    autoTable(doc, {
      startY: y,
      margin: { left: ML, right: MR },
      head: [['Port', 'Method', 'Username', 'Password']],
      body: validCreds.map(c => [
        String(c.port ?? ''),
        String(c.method ?? ''),
        String(c.username ?? ''),
        String(c.password ?? '(empty)'),
      ]),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: C.danger, textColor: C.white, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [255, 245, 245] as [number,number,number] },
      didDrawPage: () => {
        pages.n = (doc as jsPDF & { internal: { getCurrentPageInfo(): { pageNumber: number } } })
          .internal.getCurrentPageInfo().pageNumber
        addPageHeader(doc, pages.n, fwName)
        addPageFooter(doc, ts)
      },
    })
    addPageFooter(doc, ts)
  }

  // ── save ─────────────────────────────────────────────────────────────────
  const safeName = fwName.replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 60)
  doc.save(`FirmScan_${safeName}.pdf`)
}
